- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /root/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /root/Service2.yml
     - name: create new deployment
       command: kubectl apply -f /root/Deployment2.yml

