kind: Deployment
apiVersion: apps/v1
metadata:
   name: monapp
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: monapp
   template:
      metadata:
        labels:
          app: monapp
      spec:
       containers:
        - name: monapp
          image: fyfytamft/pipeline-kube
          imagePullPolicy: Always
          ports:
          - containerPort: 80