kind: Deployment
apiVersion: apps/v1
metadata:
   name: monapp
   labels:
     app: monapp
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: monapp
   template:
      metadata:
        labels:
          app: monapp
      spec:
        containers:
          - name: monapp
            image: fyfytamft/pipeline-kube
            ports:
            - containerPort: 80
        imagePullSecrets:
        - name: registry-secret     
---
apiVersion: v1
kind: Service
metadata:
  name: monapp
spec:
  selector:
    app: monapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monapp-ingress
  namespace: default

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - tongasoakubernetes.ddns.net
    secretName: monapp
  rules:
  - host: tongasoakubernetes.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monapp
            port:
              number: 80
