kind: Service                             
apiVersion: v1
metadata:
  name: monapp
  labels:
    app: monapp
spec:
  ports:
    - protocol: TCP
      port: 80                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: monapp                    
  type: LoadBalancer
  externalIPs:
    - 173.230.130.238                 
